baseurl: "/"
title: Ru Hickson
theme: ghostwriter
languageCode: en-us
copyright: My Name
disqusShortname: XXX
googleAnalytics: XXX
pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: Ru Hickson
  profile: ""

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: Ru's Blog
  description: Maths, R, Games, Sports, Social Good
  github: "https://github.com/ruhickson"
  linkedin: "https://www.linkedin.com/ruhickson/"
  twitter: "https://twitter.com/ruhickson"
  stackoverflow: "https://stackoverflow.com/users/ruhksn"
  opengraph: true
  shareTwitter: true
  rss: true
  shareFacebook: true
  shareLinkedIn: false
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""
  # If you want to use plausible(https://plausible.io) for analytics, add this section
  plausibleAnalytics:
    domain: ""
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL: ""

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Blog
      url: /
      weight: 1
    - name: Projects
      url: /projects
      weight: 2
    - name: Contact
      url: /contact/
      weight: 3
    - name: About
      url: /about/
      weight: 4
    - name: NanoData
      url: /nanodata
      weight: 5
    #- name: Roarr
    #  url: /roarr
    #  weight: 6
